Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"

  config.vm.define "master" do |master|

    master.vm.hostname = "master"
    
    master.vm.network "public_network", ip:"192.168.15.195",  bridge: "wlp58s0"
    master.vm.network "private_network", ip: "192.168.56.44"

    master.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
      vb.name = "master"
    end
  end
end

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"

  config.vm.define "worker1" do |node|

    node.vm.hostname = "worker1"
    
    node.vm.network "public_network", ip:"192.168.15.196",  bridge: "wlp58s0"
    node.vm.network "private_network", ip: "192.168.56.45"

    node.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 2
      vb.name = "worker1"
    end
end
end

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"

  config.vm.define "worker2" do |node|

    node.vm.hostname = "worker2"
    
    node.vm.network "public_network", ip:"192.168.15.197",  bridge: "wlp58s0"
    node.vm.network "private_network", ip: "192.168.56.46"

    node.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 2
      vb.name = "worker2"
    end
end
end

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"

  config.vm.define "loadbalancer" do |loadbalancer|

    loadbalancer.vm.hostname = "loadbalancer"
    
    loadbalancer.vm.network "public_network", ip:"192.168.15.198",  bridge: "wlp58s0"
    loadbalancer.vm.network "private_network", ip: "192.168.56.47"

    loadbalancer.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
      vb.name = "loadbalancer"
    end
end
end